### ISSUE TITLE
Issues and Branches Tutorial for a professional github experience

### ISSUE THREAD

**Issue by Jcvita** [dylan-cancelliere/auto-dj#6]
So basically, We're not using git to its full potential. One way we can work towards such is to write needed fixes and short term goals in the issues tab. This will help us jump right in to get working instead of wonder what the fuck to do. Furthermore, One useful thing i've learned from AJ Nag is that we should use branches to differentiate certain work in progress features, and not our own work. This will ensure that everyone is working on the right code and making progress towards our end goal.

Thank you for listening to my TED talk and get to work.

**Comment by dylan-cancelliere** [comment]
Yeah so ideally how I'd like us to use branches is exactly what you said.  Right now the nav bar is only on my branch because it's not finished yet.  Bales is working on that so when he's done with the styling we'll push to master.  When you were doing node shit earlier and pushed to master without having whatever you were working on finished, it broke everyone else's code because we didn't have certain things set up the same way you did, which is the perfect use case for a branch.  If we have two different repos that's obviously going to be even more separated, but if you have a feature that's finished enough that it won't break everyone else's project and will likely remain largely unchanged for the immediate future, feel free to make a PR to merge your branch with master.

    To be clear DO NOT push directly to master.  It should be set up so you cannot, but just in case the procedure is to open a pull request to merge your branch with master, which will ping slack and when it does so everyone should make sure they pull from master before they start working again to make it less likely that we have to do merge manually later down the line.

    Definitely agree we could be using issues more though, so I'll put what I need help with up there in a moment.
